//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Nidec.Mes.PQMConnector_Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Nidec.Mes.PQMConnector_Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when creating pqm web request : {0}..
        /// </summary>
        internal static string pcce00001 {
            get {
                return ResourceManager.GetString("pcce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when getting response from pqm server : {0}..
        /// </summary>
        internal static string pcce00002 {
            get {
                return ResourceManager.GetString("pcce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OutOfMemoryException occured when deserialize pqm output json string : {0}..
        /// </summary>
        internal static string pcce00003 {
            get {
                return ResourceManager.GetString("pcce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProtocolViolationException occured when getting response from pqm server : {0}..
        /// </summary>
        internal static string pcce00004 {
            get {
                return ResourceManager.GetString("pcce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebException occured when getting response from pqm server : {0}..
        /// </summary>
        internal static string pcce00005 {
            get {
                return ResourceManager.GetString("pcce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotSupportedException occured when getting response from pqm server : {0}..
        /// </summary>
        internal static string pcce00006 {
            get {
                return ResourceManager.GetString("pcce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidOperationException occured when getting response from pqm server : {0}..
        /// </summary>
        internal static string pcce00007 {
            get {
                return ResourceManager.GetString("pcce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IOException occured when getting response from pqm server : {0}..
        /// </summary>
        internal static string pcce00008 {
            get {
                return ResourceManager.GetString("pcce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when getting response from pqm server : {0}..
        /// </summary>
        internal static string pcce00009 {
            get {
                return ResourceManager.GetString("pcce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name is not specified..
        /// </summary>
        internal static string pcce00010 {
            get {
                return ResourceManager.GetString("pcce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured when creating pqm web request : {0}..
        /// </summary>
        internal static string pcce00011 {
            get {
                return ResourceManager.GetString("pcce00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotSupportedException occured when creating pqm web request : {0}..
        /// </summary>
        internal static string pcce00012 {
            get {
                return ResourceManager.GetString("pcce00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArgumentNullException occured when creating pqm web request : {0}..
        /// </summary>
        internal static string pcce00013 {
            get {
                return ResourceManager.GetString("pcce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecurityException occured when creating pqm web request : {0}..
        /// </summary>
        internal static string pcce00014 {
            get {
                return ResourceManager.GetString("pcce00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check pqm request..
        /// </summary>
        internal static string pcci00001 {
            get {
                return ResourceManager.GetString("pcci00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response from pqm server for the request..
        /// </summary>
        internal static string pcci00002 {
            get {
                return ResourceManager.GetString("pcci00002", resourceCulture);
            }
        }
    }
}
