//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Nidec.Mes.Common.Basic.MachineMaintenance.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Nidec.Mes.Common.Basic.MachineMaintenance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap approved {
            get {
                object obj = ResourceManager.GetObject("approved", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Capture {
            get {
                object obj = ResourceManager.GetObject("Capture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string cpcc00001 {
            get {
                return ResourceManager.GetString("cpcc00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete : [{0}] ?.
        /// </summary>
        public static string cpcc00002 {
            get {
                return ResourceManager.GetString("cpcc00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different lot is existing..
        /// </summary>
        public static string cpce00001 {
            get {
                return ResourceManager.GetString("cpce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate..
        /// </summary>
        public static string cpce00002 {
            get {
                return ResourceManager.GetString("cpce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please read correct lot no for the process..
        /// </summary>
        public static string cpce00003 {
            get {
                return ResourceManager.GetString("cpce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanned tray count mismatch with registered lot data..
        /// </summary>
        public static string cpce00004 {
            get {
                return ResourceManager.GetString("cpce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split operation had already been done for the scanned lot..
        /// </summary>
        public static string cpce00005 {
            get {
                return ResourceManager.GetString("cpce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the record..
        /// </summary>
        public static string cpce00006 {
            get {
                return ResourceManager.GetString("cpce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input [{0}].
        /// </summary>
        public static string cpce00007 {
            get {
                return ResourceManager.GetString("cpce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is already registered
        ///[{0}].
        /// </summary>
        public static string cpce00008 {
            get {
                return ResourceManager.GetString("cpce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot No has been locked..
        /// </summary>
        public static string cpce00009 {
            get {
                return ResourceManager.GetString("cpce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to issue below label?
        ///{0}.
        /// </summary>
        public static string cpci00001 {
            get {
                return ResourceManager.GetString("cpci00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been printed successfully..
        /// </summary>
        public static string cpci00002 {
            get {
                return ResourceManager.GetString("cpci00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been added successfully..
        /// </summary>
        public static string cpci00003 {
            get {
                return ResourceManager.GetString("cpci00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated successfully..
        /// </summary>
        public static string cpci00004 {
            get {
                return ResourceManager.GetString("cpci00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted successfully..
        /// </summary>
        public static string cpci00005 {
            get {
                return ResourceManager.GetString("cpci00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found!.
        /// </summary>
        public static string cpci00006 {
            get {
                return ResourceManager.GetString("cpci00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to update : [{0}] ?.
        /// </summary>
        public static string mmcc00003 {
            get {
                return ResourceManager.GetString("mmcc00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete : [{0}] ?.
        /// </summary>
        public static string mmcc00004 {
            get {
                return ResourceManager.GetString("mmcc00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Data [{0}].
        /// </summary>
        public static string mmcc00005 {
            get {
                return ResourceManager.GetString("mmcc00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data already exists [{0}].
        /// </summary>
        public static string mmcc00006 {
            get {
                return ResourceManager.GetString("mmcc00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to reload : [{0}] ?.
        /// </summary>
        public static string mmcc00007 {
            get {
                return ResourceManager.GetString("mmcc00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is already registered.
        /// </summary>
        public static string mmce00001 {
            get {
                return ResourceManager.GetString("mmce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input [{0}].
        /// </summary>
        public static string mmce00002 {
            get {
                return ResourceManager.GetString("mmce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one byte characters can be used..
        /// </summary>
        public static string mmce00003 {
            get {
                return ResourceManager.GetString("mmce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code is not correct..
        /// </summary>
        public static string mmce00004 {
            get {
                return ResourceManager.GetString("mmce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language code is not correct..
        /// </summary>
        public static string mmce00005 {
            get {
                return ResourceManager.GetString("mmce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only lowercase letter or numbers can be used in  [{0}].
        /// </summary>
        public static string mmce00006 {
            get {
                return ResourceManager.GetString("mmce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numbers can be used in  [{0}].
        /// </summary>
        public static string mmce00007 {
            get {
                return ResourceManager.GetString("mmce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been changed by others [{0}].
        /// </summary>
        public static string mmce00008 {
            get {
                return ResourceManager.GetString("mmce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been added successfully..
        /// </summary>
        public static string mmci00001 {
            get {
                return ResourceManager.GetString("mmci00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated successfully..
        /// </summary>
        public static string mmci00002 {
            get {
                return ResourceManager.GetString("mmci00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted successfully..
        /// </summary>
        public static string mmci00003 {
            get {
                return ResourceManager.GetString("mmci00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].[FormName : {1}].[LoginUser : {2}] Start..
        /// </summary>
        public static string mmci00004 {
            get {
                return ResourceManager.GetString("mmci00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].[FormName : {1}].[LoginUser : {2}] End..
        /// </summary>
        public static string mmci00005 {
            get {
                return ResourceManager.GetString("mmci00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found!.
        /// </summary>
        public static string mmci00006 {
            get {
                return ResourceManager.GetString("mmci00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] successfully..
        /// </summary>
        public static string mmci00007 {
            get {
                return ResourceManager.GetString("mmci00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NG {
            get {
                object obj = ResourceManager.GetObject("NG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NG_BEAR {
            get {
                object obj = ResourceManager.GetObject("NG_BEAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap NoDaTa {
            get {
                object obj = ResourceManager.GetObject("NoDaTa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap OK_BEAR {
            get {
                object obj = ResourceManager.GetObject("OK_BEAR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap rejected {
            get {
                object obj = ResourceManager.GetObject("rejected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap STANDBY {
            get {
                object obj = ResourceManager.GetObject("STANDBY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Object is null [{0}]..
        /// </summary>
        public static string vnce00001 {
            get {
                return ResourceManager.GetString("vnce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This record is waiting to confirm or added before.
        /// </summary>
        public static string vnce00002 {
            get {
                return ResourceManager.GetString("vnce00002", resourceCulture);
            }
        }
    }
}
