//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Nidec.Mes.Framework_Server.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultRemoteCbmInvokerProxy")]
        public string DEFAULT_REMOTE_MES_SERVER_DEFAULT_SERVICE_NAME {
            get {
                return ((string)(this["DEFAULT_REMOTE_MES_SERVER_DEFAULT_SERVICE_NAME"]));
            }
            set {
                this["DEFAULT_REMOTE_MES_SERVER_DEFAULT_SERVICE_NAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultRemoteCbmInvokerProxy_2008")]
        public string DEFAULT_REMOTE_MES_SERVER_DEFAULT_2008_SERVICE_NAME {
            get {
                return ((string)(this["DEFAULT_REMOTE_MES_SERVER_DEFAULT_2008_SERVICE_NAME"]));
            }
            set {
                this["DEFAULT_REMOTE_MES_SERVER_DEFAULT_2008_SERVICE_NAME"] = value;
            }
        }
    }
}
