//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Nidec.Mes.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Nidec.Mes.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cbm Controller is not specified [{0}]..
        /// </summary>
        internal static string ffce00001 {
            get {
                return ResourceManager.GetString("ffce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name is not specified..
        /// </summary>
        internal static string ffce00002 {
            get {
                return ResourceManager.GetString("ffce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigurationErrorsException occured in access configuration file{0}..
        /// </summary>
        internal static string ffce00003 {
            get {
                return ResourceManager.GetString("ffce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file not found..
        /// </summary>
        internal static string ffce00004 {
            get {
                return ResourceManager.GetString("ffce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usersettings data not found in the configuration file..
        /// </summary>
        internal static string ffce00005 {
            get {
                return ResourceManager.GetString("ffce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found for usersettings in the configuration file..
        /// </summary>
        internal static string ffce00006 {
            get {
                return ResourceManager.GetString("ffce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found for the [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00007 {
            get {
                return ResourceManager.GetString("ffce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when kill the process : {0}.
        /// </summary>
        internal static string ffce00008 {
            get {
                return ResourceManager.GetString("ffce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured : {0}.
        /// </summary>
        internal static string ffce00009 {
            get {
                return ResourceManager.GetString("ffce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error has occurred again while handling unexpected exception..
        /// </summary>
        internal static string ffce00010 {
            get {
                return ResourceManager.GetString("ffce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when kill the process during application initialization : {0}.
        /// </summary>
        internal static string ffce00011 {
            get {
                return ResourceManager.GetString("ffce00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [APPLICATION_HEADER] [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00012 {
            get {
                return ResourceManager.GetString("ffce00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CONNECTION_STRING] [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00013 {
            get {
                return ResourceManager.GetString("ffce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AUTHENTIFICATE_FLAG] [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00014 {
            get {
                return ResourceManager.GetString("ffce00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SERVER_TIME_ZONE] [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00015 {
            get {
                return ResourceManager.GetString("ffce00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application configuration setting value is null..
        /// </summary>
        internal static string ffce00016 {
            get {
                return ResourceManager.GetString("ffce00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application configuration setting data not found..
        /// </summary>
        internal static string ffce00017 {
            get {
                return ResourceManager.GetString("ffce00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured remote service object creation : {0}..
        /// </summary>
        internal static string ffce00018 {
            get {
                return ResourceManager.GetString("ffce00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string is not specified..
        /// </summary>
        internal static string ffce00019 {
            get {
                return ResourceManager.GetString("ffce00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured during password encryption..
        /// </summary>
        internal static string ffce00020 {
            get {
                return ResourceManager.GetString("ffce00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured in wait progress form running..
        /// </summary>
        internal static string ffce00021 {
            get {
                return ResourceManager.GetString("ffce00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Connection error : [{0}]..
        /// </summary>
        internal static string ffce00022 {
            get {
                return ResourceManager.GetString("ffce00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationException occured in cbm execution [{0}]..
        /// </summary>
        internal static string ffce00023 {
            get {
                return ResourceManager.GetString("ffce00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemException occured in cbm execution [{0}]..
        /// </summary>
        internal static string ffce00024 {
            get {
                return ResourceManager.GetString("ffce00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexcepted error occured in cbm execution [{0}]..
        /// </summary>
        internal static string ffce00025 {
            get {
                return ResourceManager.GetString("ffce00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnhandledException occured in rollback transaction [{0}]..
        /// </summary>
        internal static string ffce00026 {
            get {
                return ResourceManager.GetString("ffce00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured in dbconnection close [{0}]..
        /// </summary>
        internal static string ffce00027 {
            get {
                return ResourceManager.GetString("ffce00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidOperationException occured in rollback transaction [{0}]..
        /// </summary>
        internal static string ffce00028 {
            get {
                return ResourceManager.GetString("ffce00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] settings file not found..
        /// </summary>
        internal static string ffce00029 {
            get {
                return ResourceManager.GetString("ffce00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [APPLICATION_ENVIRONMENT_SETTINGS] [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00030 {
            get {
                return ResourceManager.GetString("ffce00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid keyname in the settings file to get the value..
        /// </summary>
        internal static string ffce00031 {
            get {
                return ResourceManager.GetString("ffce00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullReferenceException occurs in getting configuration..
        /// </summary>
        internal static string ffce00032 {
            get {
                return ResourceManager.GetString("ffce00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullReferenceException occurs in getting sectionname from configuration..
        /// </summary>
        internal static string ffce00033 {
            get {
                return ResourceManager.GetString("ffce00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value not found for the [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00034 {
            get {
                return ResourceManager.GetString("ffce00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section not found for the [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00035 {
            get {
                return ResourceManager.GetString("ffce00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element not found for the [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00036 {
            get {
                return ResourceManager.GetString("ffce00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [APPLICATION_ENVIRONMENT_HEADER] [{0}] in the configuration file..
        /// </summary>
        internal static string ffce00037 {
            get {
                return ResourceManager.GetString("ffce00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select factory..
        /// </summary>
        internal static string ffce00038 {
            get {
                return ResourceManager.GetString("ffce00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name is not specified in DefaultMySqlParameterList..
        /// </summary>
        internal static string ffce00039 {
            get {
                return ResourceManager.GetString("ffce00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string is not specified in DefaultMySqlCbmInvoker..
        /// </summary>
        internal static string ffce00040 {
            get {
                return ResourceManager.GetString("ffce00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cbm Controller is not specified [{0}] in MySqlCbmInvoker..
        /// </summary>
        internal static string ffce00041 {
            get {
                return ResourceManager.GetString("ffce00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationException occured in cbm execution [{0}] in MySqlCbmInvoker..
        /// </summary>
        internal static string ffce00042 {
            get {
                return ResourceManager.GetString("ffce00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemException occured in cbm execution [{0}]in MySqlCbmInvoker..
        /// </summary>
        internal static string ffce00043 {
            get {
                return ResourceManager.GetString("ffce00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexcepted error occured in cbm execution [{0}]in MySqlCbmInvoker..
        /// </summary>
        internal static string ffce00044 {
            get {
                return ResourceManager.GetString("ffce00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured in dbconnection close [{0}]in MySqlCbmInvoker..
        /// </summary>
        internal static string ffce00045 {
            get {
                return ResourceManager.GetString("ffce00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidOperationException occured in rollback transaction [{0}]in MySqlCbmInvoker..
        /// </summary>
        internal static string ffce00046 {
            get {
                return ResourceManager.GetString("ffce00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnhandledException occured in rollback transaction [{0}]in MySqlCbmInvoker..
        /// </summary>
        internal static string ffce00047 {
            get {
                return ResourceManager.GetString("ffce00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicationsettingsfilename is null in DefaultStaticCachedConfigurationReader..
        /// </summary>
        internal static string ffce00048 {
            get {
                return ResourceManager.GetString("ffce00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configvaluemap hashtable instance not created in DefaultStaticCachedConfigurationReader..
        /// </summary>
        internal static string ffce00049 {
            get {
                return ResourceManager.GetString("ffce00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batchmain settingsfilename is null in BatchStaticCachedConfigurationReader..
        /// </summary>
        internal static string ffce00050 {
            get {
                return ResourceManager.GetString("ffce00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string llce00001 {
            get {
                return ResourceManager.GetString("llce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input login..
        /// </summary>
        internal static string llce00002 {
            get {
                return ResourceManager.GetString("llce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Password..
        /// </summary>
        internal static string llce00003 {
            get {
                return ResourceManager.GetString("llce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide  valid input..
        /// </summary>
        internal static string llce00004 {
            get {
                return ResourceManager.GetString("llce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not found for the user [{0}]..
        /// </summary>
        internal static string llce00005 {
            get {
                return ResourceManager.GetString("llce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid Menu..
        /// </summary>
        internal static string llce00006 {
            get {
                return ResourceManager.GetString("llce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occurred in the LDAP authentification process[{0}]..
        /// </summary>
        internal static string llce00007 {
            get {
                return ResourceManager.GetString("llce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide valid authenticate flag 1(Ldap) or 2(Local user).
        ///Current value :[{0}]..
        /// </summary>
        internal static string llce00008 {
            get {
                return ResourceManager.GetString("llce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm password not matching..
        /// </summary>
        internal static string llce00009 {
            get {
                return ResourceManager.GetString("llce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input new password ..
        /// </summary>
        internal static string llce00010 {
            get {
                return ResourceManager.GetString("llce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input confirm password..
        /// </summary>
        internal static string llce00011 {
            get {
                return ResourceManager.GetString("llce00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password should not be same as old password..
        /// </summary>
        internal static string llce00012 {
            get {
                return ResourceManager.GetString("llce00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is error.Please input again!.
        /// </summary>
        internal static string llce00013 {
            get {
                return ResourceManager.GetString("llce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectDisposedException has occurred in the LDAP authentification send request process[{0}]..
        /// </summary>
        internal static string llce00014 {
            get {
                return ResourceManager.GetString("llce00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArgumentNullException has occurred in the LDAP authentification send request process[{0}]..
        /// </summary>
        internal static string llce00015 {
            get {
                return ResourceManager.GetString("llce00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotSupportedException has occurred in the LDAP authentification send request process[{0}]..
        /// </summary>
        internal static string llce00016 {
            get {
                return ResourceManager.GetString("llce00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LdapException has occurred in the LDAP authentification send request process[{0}]..
        /// </summary>
        internal static string llce00017 {
            get {
                return ResourceManager.GetString("llce00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectoryOperationException has occurred in the LDAP authentification send request process[{0}]..
        /// </summary>
        internal static string llce00018 {
            get {
                return ResourceManager.GetString("llce00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectDisposedException has occurred in the LDAP authentification bind request process with network credential[{0}]..
        /// </summary>
        internal static string llce00019 {
            get {
                return ResourceManager.GetString("llce00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LdapException has occurred in the LDAP authentification bind request process with network credential[{0}]..
        /// </summary>
        internal static string llce00020 {
            get {
                return ResourceManager.GetString("llce00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidOperationException has occurred in the LDAP authentification bind request process with network credential[{0}]..
        /// </summary>
        internal static string llce00021 {
            get {
                return ResourceManager.GetString("llce00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been updated successfully. Please login again..
        /// </summary>
        internal static string llci00001 {
            get {
                return ResourceManager.GetString("llci00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure want to logout ?.
        /// </summary>
        internal static string llci00002 {
            get {
                return ResourceManager.GetString("llci00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NIDEC_Logo_small {
            get {
                object obj = ResourceManager.GetObject("NIDEC_Logo_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
