//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Nidec.Mes.GlobalMasterMaintenance.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Nidec.Mes.GlobalMasterMaintenance.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CavityCode.
        /// </summary>
        internal static string CavityCode {
            get {
                return ResourceManager.GetString("CavityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CavityName.
        /// </summary>
        internal static string CavityName {
            get {
                return ResourceManager.GetString("CavityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string LOCATION_TYPE_PROCESS {
            get {
                return ResourceManager.GetString("LOCATION_TYPE_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        internal static string LOCATION_TYPE_WAREHOUSE {
            get {
                return ResourceManager.GetString("LOCATION_TYPE_WAREHOUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string mmcc00001 {
            get {
                return ResourceManager.GetString("mmcc00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to add {0} ?.
        /// </summary>
        internal static string mmcc00002 {
            get {
                return ResourceManager.GetString("mmcc00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to update : [{0}] ?.
        /// </summary>
        internal static string mmcc00003 {
            get {
                return ResourceManager.GetString("mmcc00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete : [{0}] ?.
        /// </summary>
        internal static string mmcc00004 {
            get {
                return ResourceManager.GetString("mmcc00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Data [{0}].
        /// </summary>
        internal static string mmcc00005 {
            get {
                return ResourceManager.GetString("mmcc00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data already exists [{0}].
        /// </summary>
        internal static string mmcc00006 {
            get {
                return ResourceManager.GetString("mmcc00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is already registered
        ///[{0}].
        /// </summary>
        internal static string mmce00001 {
            get {
                return ResourceManager.GetString("mmce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input [{0}].
        /// </summary>
        internal static string mmce00002 {
            get {
                return ResourceManager.GetString("mmce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one byte characters can be used..
        /// </summary>
        internal static string mmce00003 {
            get {
                return ResourceManager.GetString("mmce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code is not correct..
        /// </summary>
        internal static string mmce00004 {
            get {
                return ResourceManager.GetString("mmce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language code is not correct..
        /// </summary>
        internal static string mmce00005 {
            get {
                return ResourceManager.GetString("mmce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only lowercase letter or numbers can be used in  [{0}].
        /// </summary>
        internal static string mmce00006 {
            get {
                return ResourceManager.GetString("mmce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cannot be delete due to having relation with [ {0} ].
        /// </summary>
        internal static string mmce00007 {
            get {
                return ResourceManager.GetString("mmce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file does not have sheet [{0}].
        /// </summary>
        internal static string mmce00008 {
            get {
                return ResourceManager.GetString("mmce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate [{0}].
        /// </summary>
        internal static string mmce00009 {
            get {
                return ResourceManager.GetString("mmce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid [{0}].
        /// </summary>
        internal static string mmce00010 {
            get {
                return ResourceManager.GetString("mmce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty [{0}].
        /// </summary>
        internal static string mmce00011 {
            get {
                return ResourceManager.GetString("mmce00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is already registered
        ///[{0}].
        /// </summary>
        internal static string mmce00012 {
            get {
                return ResourceManager.GetString("mmce00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select valid mold for search..
        /// </summary>
        internal static string mmce00013 {
            get {
                return ResourceManager.GetString("mmce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move the processwork up with greater sequence no for same processwork..
        /// </summary>
        internal static string mmce00014 {
            get {
                return ResourceManager.GetString("mmce00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot move the processwork down with less sequence no for same processwork..
        /// </summary>
        internal static string mmce00015 {
            get {
                return ResourceManager.GetString("mmce00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select only one stock location for process..
        /// </summary>
        internal static string mmce00016 {
            get {
                return ResourceManager.GetString("mmce00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] length should be less than or equal to [{1}].
        /// </summary>
        internal static string mmce00017 {
            get {
                return ResourceManager.GetString("mmce00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoldCode [{0}] not exist in Cavity Sheet.
        /// </summary>
        internal static string mmce00018 {
            get {
                return ResourceManager.GetString("mmce00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Std Cycle time shoud be greater than zero..
        /// </summary>
        internal static string mmce00019 {
            get {
                return ResourceManager.GetString("mmce00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate record exists in cavity sheet MoldCode [{0}] and CavityName[{1}].
        /// </summary>
        internal static string mmce00020 {
            get {
                return ResourceManager.GetString("mmce00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation of sapitem [{0}] with [mes item, model, std cycletime, drawing no].
        /// </summary>
        internal static string mmce00021 {
            get {
                return ResourceManager.GetString("mmce00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SapItem [{0}] should have 1 : 1 relation with MoldItem ..
        /// </summary>
        internal static string mmce00022 {
            get {
                return ResourceManager.GetString("mmce00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input valid numeric value..
        /// </summary>
        internal static string mmce00023 {
            get {
                return ResourceManager.GetString("mmce00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured in excel upload validation..
        /// </summary>
        internal static string mmce00024 {
            get {
                return ResourceManager.GetString("mmce00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sapitem data not found..
        /// </summary>
        internal static string mmce00025 {
            get {
                return ResourceManager.GetString("mmce00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mold data not found..
        /// </summary>
        internal static string mmce00026 {
            get {
                return ResourceManager.GetString("mmce00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid MoldCode [{0}] in Cavity sheet.
        /// </summary>
        internal static string mmce00027 {
            get {
                return ResourceManager.GetString("mmce00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been added successfully..
        /// </summary>
        internal static string mmci00001 {
            get {
                return ResourceManager.GetString("mmci00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been updated successfully..
        /// </summary>
        internal static string mmci00002 {
            get {
                return ResourceManager.GetString("mmci00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record has been deleted successfully..
        /// </summary>
        internal static string mmci00003 {
            get {
                return ResourceManager.GetString("mmci00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].[FormName : {1}].[LoginUser : {2}] Start..
        /// </summary>
        internal static string mmci00004 {
            get {
                return ResourceManager.GetString("mmci00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].[FormName : {1}].[LoginUser : {2}] End..
        /// </summary>
        internal static string mmci00005 {
            get {
                return ResourceManager.GetString("mmci00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found!.
        /// </summary>
        internal static string mmci00006 {
            get {
                return ResourceManager.GetString("mmci00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already record has been deleted by another user..
        /// </summary>
        internal static string mmci00007 {
            get {
                return ResourceManager.GetString("mmci00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter minimum 4 Charecter for [ {0} ].
        /// </summary>
        internal static string mmci00008 {
            get {
                return ResourceManager.GetString("mmci00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string mmci00009 {
            get {
                return ResourceManager.GetString("mmci00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data uploaded successfully..
        /// </summary>
        internal static string mmci00010 {
            get {
                return ResourceManager.GetString("mmci00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found. [{0}].
        /// </summary>
        internal static string mmci00011 {
            get {
                return ResourceManager.GetString("mmci00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User master exported successfully...
        /// </summary>
        internal static string mmci00012 {
            get {
                return ResourceManager.GetString("mmci00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] already exists, Click [YES] to overwrite the original file and cannot be restored after overwrittten..
        /// </summary>
        internal static string mmci00013 {
            get {
                return ResourceManager.GetString("mmci00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select any Users from the List..
        /// </summary>
        internal static string mmci00014 {
            get {
                return ResourceManager.GetString("mmci00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Upload Excel File.
        /// </summary>
        internal static string mmci00015 {
            get {
                return ResourceManager.GetString("mmci00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct excel data before adding.
        /// </summary>
        internal static string mmci00016 {
            get {
                return ResourceManager.GetString("mmci00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha numeric value only allowed in [{0}].
        /// </summary>
        internal static string mmci00017 {
            get {
                return ResourceManager.GetString("mmci00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric value only allowed in [{0}].
        /// </summary>
        internal static string mmci00018 {
            get {
                return ResourceManager.GetString("mmci00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Work Code is not correct.
        /// </summary>
        internal static string mmci00019 {
            get {
                return ResourceManager.GetString("mmci00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] sheet not exists in the excel.
        /// </summary>
        internal static string mmci00020 {
            get {
                return ResourceManager.GetString("mmci00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The standard EXCEL file is downloaded..
        /// </summary>
        internal static string mmci00021 {
            get {
                return ResourceManager.GetString("mmci00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data cannot be deleted due to data association [INSPECTION PROCESS].
        /// </summary>
        internal static string mmci00022 {
            get {
                return ResourceManager.GetString("mmci00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing Result Count value [{0}] will be update all Instruction Detail Result Count Values [{1}]..
        /// </summary>
        internal static string mmci00023 {
            get {
                return ResourceManager.GetString("mmci00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click Specification to input InspectionSpecification..
        /// </summary>
        internal static string mmci00024 {
            get {
                return ResourceManager.GetString("mmci00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click TestInstruction to input TestInstruction..
        /// </summary>
        internal static string mmci00025 {
            get {
                return ResourceManager.GetString("mmci00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click InspectionItem to input InspectionItem..
        /// </summary>
        internal static string mmci00026 {
            get {
                return ResourceManager.GetString("mmci00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click ItemLine to input ItemLine..
        /// </summary>
        internal static string mmci00027 {
            get {
                return ResourceManager.GetString("mmci00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click InspectionProcess to Input InspectionProcess.
        /// </summary>
        internal static string mmci00028 {
            get {
                return ResourceManager.GetString("mmci00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Specification Record is Exist for the selected Inspection Item. Please delete the Inspection  specification data..
        /// </summary>
        internal static string mmci00029 {
            get {
                return ResourceManager.GetString("mmci00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date is Greater than To date, Please select the valid Date..
        /// </summary>
        internal static string mmci00030 {
            get {
                return ResourceManager.GetString("mmci00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching Data is in progress.
        /// </summary>
        internal static string mmci00031 {
            get {
                return ResourceManager.GetString("mmci00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mold data exported successfully.
        /// </summary>
        internal static string mmci00032 {
            get {
                return ResourceManager.GetString("mmci00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data not correct in ExcelSheet.
        /// </summary>
        internal static string mmci00033 {
            get {
                return ResourceManager.GetString("mmci00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty [{0}].
        /// </summary>
        internal static string mmci00034 {
            get {
                return ResourceManager.GetString("mmci00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click TestInstruction to input TestInstruction detail..
        /// </summary>
        internal static string mmci00035 {
            get {
                return ResourceManager.GetString("mmci00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Process [{0}], Please wait..
        /// </summary>
        internal static string mmci00036 {
            get {
                return ResourceManager.GetString("mmci00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating [{0}] [{1}], Please Wait..
        /// </summary>
        internal static string mmci00037 {
            get {
                return ResourceManager.GetString("mmci00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting [{0}] [{1}], Please Wait..
        /// </summary>
        internal static string mmci00038 {
            get {
                return ResourceManager.GetString("mmci00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Format[{0}], Please wait..
        /// </summary>
        internal static string mmci00039 {
            get {
                return ResourceManager.GetString("mmci00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record is already registered
        ///[{0}],[{1}].
        /// </summary>
        internal static string mmci00040 {
            get {
                return ResourceManager.GetString("mmci00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SapItemGroupId not found for the the selected Item Code[{0}]..
        /// </summary>
        internal static string mmci00041 {
            get {
                return ResourceManager.GetString("mmci00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Format [{0}], Please Wait..
        /// </summary>
        internal static string mmci00042 {
            get {
                return ResourceManager.GetString("mmci00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating [{0}] [{1}], Please Wait..
        /// </summary>
        internal static string mmci00043 {
            get {
                return ResourceManager.GetString("mmci00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Name [{0}], Already Exist..
        /// </summary>
        internal static string mmci00044 {
            get {
                return ResourceManager.GetString("mmci00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Item[{0}], Please wait..
        /// </summary>
        internal static string mmci00045 {
            get {
                return ResourceManager.GetString("mmci00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select minimum one [{0}]..
        /// </summary>
        internal static string mmci00046 {
            get {
                return ResourceManager.GetString("mmci00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input any one StdCycleTime in the grid..
        /// </summary>
        internal static string mmci00047 {
            get {
                return ResourceManager.GetString("mmci00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection item [{0}] doesn&apos;t have a data for Inspection specification &amp; Test instruction. Do you want to copy ?.
        /// </summary>
        internal static string mmci00048 {
            get {
                return ResourceManager.GetString("mmci00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelCode.
        /// </summary>
        internal static string ModelCode {
            get {
                return ResourceManager.GetString("ModelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoldCategoryCode.
        /// </summary>
        internal static string MoldCategoryCode {
            get {
                return ResourceManager.GetString("MoldCategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MoldItemCode.
        /// </summary>
        internal static string MoldItemCode {
            get {
                return ResourceManager.GetString("MoldItemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleLine.
        /// </summary>
        internal static string SINGLE_LINE {
            get {
                return ResourceManager.GetString("SINGLE_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleLineandSingleMachine.
        /// </summary>
        internal static string SINGLE_LINE_MACHINE {
            get {
                return ResourceManager.GetString("SINGLE_LINE_MACHINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SingleMachine.
        /// </summary>
        internal static string SINGLE_MACHINE {
            get {
                return ResourceManager.GetString("SINGLE_MACHINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StdCycleTime.
        /// </summary>
        internal static string StdCycleTime {
            get {
                return ResourceManager.GetString("StdCycleTime", resourceCulture);
            }
        }
    }
}
