//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Nidec.Mes.Framework_Batch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Nidec.Mes.Framework_Batch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Process will Start..
        /// </summary>
        internal static string fbcd00001 {
            get {
                return ResourceManager.GetString("fbcd00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Process Ended..
        /// </summary>
        internal static string fbcd00002 {
            get {
                return ResourceManager.GetString("fbcd00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CONNECTION_STRING] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00001 {
            get {
                return ResourceManager.GetString("fbce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SERVER_TIME_ZONE] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00002 {
            get {
                return ResourceManager.GetString("fbce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured in the batchmain execution process..
        /// </summary>
        internal static string fbce000021 {
            get {
                return ResourceManager.GetString("fbce000021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [APPLICATION_ENVIRONMENT_SETTINGS] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00003 {
            get {
                return ResourceManager.GetString("fbce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_BATCH_USER] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00004 {
            get {
                return ResourceManager.GetString("fbce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DEFAULT_BATCH_FACTORYCODE] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00005 {
            get {
                return ResourceManager.GetString("fbce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BATCH_EXECUTION_TYPE] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00006 {
            get {
                return ResourceManager.GetString("fbce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BATCH_EXECUTION_WAIT_INTERVAL] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00007 {
            get {
                return ResourceManager.GetString("fbce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BATCH_EXECUTION_RETRY_COUNT_ON_EXCEPTION] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00008 {
            get {
                return ResourceManager.GetString("fbce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BATCH_EXECUTION_RETRY_WAIT_INTERVAL_ON_EXCEPTION] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00009 {
            get {
                return ResourceManager.GetString("fbce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PREVENT_MULTIPLE_INVOKE] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00010 {
            get {
                return ResourceManager.GetString("fbce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PREVENT_MULTIPLE_INVOKE_RETRY_COUNT] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00011 {
            get {
                return ResourceManager.GetString("fbce00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PREVENT_MULTIPLE_INVOKE_WAIT_INTERVAL] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00012 {
            get {
                return ResourceManager.GetString("fbce00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BATCH_PROCESS_ID_FOR_MULTIPLE_INVOKE] [{0}] in the configuration file..
        /// </summary>
        internal static string fbce00013 {
            get {
                return ResourceManager.GetString("fbce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application configuration setting value is null..
        /// </summary>
        internal static string fbce00014 {
            get {
                return ResourceManager.GetString("fbce00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application configuration setting data not found..
        /// </summary>
        internal static string fbce00015 {
            get {
                return ResourceManager.GetString("fbce00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured : {0} in Handle exception.
        /// </summary>
        internal static string fbce00016 {
            get {
                return ResourceManager.GetString("fbce00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error has occurred again while handling unexpected exception..
        /// </summary>
        internal static string fbce00017 {
            get {
                return ResourceManager.GetString("fbce00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error has occurred in abnormal end..
        /// </summary>
        internal static string fbce00018 {
            get {
                return ResourceManager.GetString("fbce00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win32Exception occured when kill the process : {0}.
        /// </summary>
        internal static string fbce00019 {
            get {
                return ResourceManager.GetString("fbce00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotSupportedException occured when kill the process : {0}.
        /// </summary>
        internal static string fbce00020 {
            get {
                return ResourceManager.GetString("fbce00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidOperationException occured when kill the process : {0}.
        /// </summary>
        internal static string fbce00021 {
            get {
                return ResourceManager.GetString("fbce00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured in batch after retry count completed..
        /// </summary>
        internal static string fbce00022 {
            get {
                return ResourceManager.GetString("fbce00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BatchMain class instance is not available..
        /// </summary>
        internal static string fbce00023 {
            get {
                return ResourceManager.GetString("fbce00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured : {0} in batch complete process.
        /// </summary>
        internal static string fbce00024 {
            get {
                return ResourceManager.GetString("fbce00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArgumentOutOfRangeException occured in thread sleep of execution interval..
        /// </summary>
        internal static string fbce00025 {
            get {
                return ResourceManager.GetString("fbce00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArgumentOutOfRangeException occured in thread sleep of retry on exception execution interval..
        /// </summary>
        internal static string fbce00026 {
            get {
                return ResourceManager.GetString("fbce00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ArgumentOutOfRangeException occured in thread sleep of retry of multiple invoke execution interval..
        /// </summary>
        internal static string fbce00027 {
            get {
                return ResourceManager.GetString("fbce00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch retry on exception reached max count..
        /// </summary>
        internal static string fbce00028 {
            get {
                return ResourceManager.GetString("fbce00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured : {0} in batch start process in prevent multiple invoke.
        /// </summary>
        internal static string fbce00029 {
            get {
                return ResourceManager.GetString("fbce00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured : {0} in batch complete process after reached max retry count..
        /// </summary>
        internal static string fbce00030 {
            get {
                return ResourceManager.GetString("fbce00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured : {0} in batch complete process on batchexecution..
        /// </summary>
        internal static string fbce00031 {
            get {
                return ResourceManager.GetString("fbce00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured : {0} in batch complete process on batchexecution infinity loop..
        /// </summary>
        internal static string fbce00032 {
            get {
                return ResourceManager.GetString("fbce00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured : {0} in batch complete process on batchexecution retry..
        /// </summary>
        internal static string fbce00033 {
            get {
                return ResourceManager.GetString("fbce00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured : {0} in batch execution..
        /// </summary>
        internal static string fbce00034 {
            get {
                return ResourceManager.GetString("fbce00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BATCH_EXECUTION_TYPE] in configuration file must be &apos;0&apos; or &apos;1&apos;..
        /// </summary>
        internal static string fbce00035 {
            get {
                return ResourceManager.GetString("fbce00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BATCH_EXECUTION_RETRY_COUNT_ON_EXCEPTION] in configuration file must be in integer format..
        /// </summary>
        internal static string fbce00036 {
            get {
                return ResourceManager.GetString("fbce00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PREVENT_MULTIPLE_INVOKE] in configuration file must be boolean value..
        /// </summary>
        internal static string fbce00037 {
            get {
                return ResourceManager.GetString("fbce00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occurred in Environment.Exit method in exceptionhandler..
        /// </summary>
        internal static string fbce00038 {
            get {
                return ResourceManager.GetString("fbce00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occurred in Environment.Exit method in batchcontroller..
        /// </summary>
        internal static string fbce00039 {
            get {
                return ResourceManager.GetString("fbce00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BATCH_EXECUTION_RETRY_COUNT_ON_EXCEPTION] in configuration file should not be less than 0..
        /// </summary>
        internal static string fbce00040 {
            get {
                return ResourceManager.GetString("fbce00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PREVENT_MULTIPLE_INVOKE_RETRY_COUNT] in configuration file must be in integer format..
        /// </summary>
        internal static string fbce00041 {
            get {
                return ResourceManager.GetString("fbce00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PREVENT_MULTIPLE_INVOKE_RETRY_COUNT] in configuration file should not be less than 0..
        /// </summary>
        internal static string fbce00042 {
            get {
                return ResourceManager.GetString("fbce00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occurred in batchapplicationinitializer..
        /// </summary>
        internal static string fbce00043 {
            get {
                return ResourceManager.GetString("fbce00043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BATCH_EXECUTION_RETRY_WAIT_INTERVAL_ON_EXCEPTION] in configuration file must be timespan value..
        /// </summary>
        internal static string fbce00044 {
            get {
                return ResourceManager.GetString("fbce00044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [BATCH_EXECUTION_RETRY_WAIT_INTERVAL_ON_EXCEPTION] in configuration file timespan value should be greater than 0..
        /// </summary>
        internal static string fbce00045 {
            get {
                return ResourceManager.GetString("fbce00045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PREVENT_MULTIPLE_INVOKE_WAIT_INTERVAL] in configuration file must be timespan value..
        /// </summary>
        internal static string fbce00046 {
            get {
                return ResourceManager.GetString("fbce00046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PREVENT_MULTIPLE_INVOKE_WAIT_INTERVAL] in configuration file timespan value should be greater than 0..
        /// </summary>
        internal static string fbce00047 {
            get {
                return ResourceManager.GetString("fbce00047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild to Delete Data..
        /// </summary>
        internal static string fbce00048 {
            get {
                return ResourceManager.GetString("fbce00048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faild to Revert Data..
        /// </summary>
        internal static string fbce00049 {
            get {
                return ResourceManager.GetString("fbce00049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batchmain settingsfilename is null in DefaultBatchController..
        /// </summary>
        internal static string fbce00050 {
            get {
                return ResourceManager.GetString("fbce00050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BatchStaticCachedConfigurationReader instance not created in BatchConfigurationDataTypeEnum..
        /// </summary>
        internal static string fbce00051 {
            get {
                return ResourceManager.GetString("fbce00051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured while creating BatchStaticCachedConfigurationReader instance in DefaultBatchController..
        /// </summary>
        internal static string fbce00052 {
            get {
                return ResourceManager.GetString("fbce00052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BatchStaticCachedConfigurationReader is null while call GetValue in BatchConfigurationDataTypeEnum..
        /// </summary>
        internal static string fbce00053 {
            get {
                return ResourceManager.GetString("fbce00053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured while SetConfigurationReader instance in DefaultBatchController..
        /// </summary>
        internal static string fbce00054 {
            get {
                return ResourceManager.GetString("fbce00054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occured : {0} in batch check is stop requested after batch execution...
        /// </summary>
        internal static string fbce00055 {
            get {
                return ResourceManager.GetString("fbce00055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Stop Batch..
        /// </summary>
        internal static string fbce00056 {
            get {
                return ResourceManager.GetString("fbce00056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch has been started successfully..
        /// </summary>
        internal static string fbci00001 {
            get {
                return ResourceManager.GetString("fbci00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch is already running..
        /// </summary>
        internal static string fbci00002 {
            get {
                return ResourceManager.GetString("fbci00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch has been completed with code - [{0}]..
        /// </summary>
        internal static string fbci00003 {
            get {
                return ResourceManager.GetString("fbci00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting thread until [BATCH_EXECUTION_INTERVAL] specified in the configuration file. [{0}].
        /// </summary>
        internal static string fbci00004 {
            get {
                return ResourceManager.GetString("fbci00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch calculation is now restarting due to exception occured [Retry Count : [{0}]]..
        /// </summary>
        internal static string fbci00005 {
            get {
                return ResourceManager.GetString("fbci00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting thread until [BATCH_EXECUTION_RETRY_WAIT_INTERVAL_ON_EXCEPTION] specified in the configuration file.  [{0}].
        /// </summary>
        internal static string fbci00006 {
            get {
                return ResourceManager.GetString("fbci00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch calculation is now restarting due to multiple invoke check [Retry Count : [{0}]]..
        /// </summary>
        internal static string fbci00007 {
            get {
                return ResourceManager.GetString("fbci00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting thread until [PREVENT_MULTIPLE_INVOKE_WAIT_INTERVAL] specified in the configuration file. [{0}].
        /// </summary>
        internal static string fbci00008 {
            get {
                return ResourceManager.GetString("fbci00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch data has not available in t_batch_process to start..
        /// </summary>
        internal static string fbci00009 {
            get {
                return ResourceManager.GetString("fbci00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Available to Revert.
        /// </summary>
        internal static string fbci00010 {
            get {
                return ResourceManager.GetString("fbci00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure to Delete this Data?.
        /// </summary>
        internal static string fbci00011 {
            get {
                return ResourceManager.GetString("fbci00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch data has not available in t_batch_process to stop...
        /// </summary>
        internal static string fbci00012 {
            get {
                return ResourceManager.GetString("fbci00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You sure to Stop this Batch?.
        /// </summary>
        internal static string fbci00013 {
            get {
                return ResourceManager.GetString("fbci00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch has been completed after stop requested by administrator..
        /// </summary>
        internal static string fbci00014 {
            get {
                return ResourceManager.GetString("fbci00014", resourceCulture);
            }
        }
    }
}
