//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Nidec.Mes.Framework_Batch.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_BATCH_EXECUTION_SUCCESS {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_BATCH_EXECUTION_SUCCESS"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_BATCH_EXECUTION_SUCCESS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("305")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_COMPLETE_EXCEPTION {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_COMPLETE_EXCEPTION"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_COMPLETE_EXCEPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("402")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_RETRY_THREAD_WAIT_EXCEPTION {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_RETRY_THREAD_WAIT_EXCEPTION"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_RETRY_THREAD_WAIT_EXCEPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("304")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_THREAD_WAIT_EXCEPTION {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_THREAD_WAIT_EXCEPTION"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_THREAD_WAIT_EXCEPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("501")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_RETRY_EXECUTION_ON_EXCEPTION_THREAD_WAIT_EXCEPTION {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_RETRY_EXECUTION_ON_EXCEPTION_THREAD_WAIT_EXCEPTI" +
                    "ON"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_RETRY_EXECUTION_ON_EXCEPTION_THREAD_WAIT_EXCEPTI" +
                    "ON"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("502")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_RETRY_EXECUTION_ON_EXCEPTION_REACHED_MAX_COUNT {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_RETRY_EXECUTION_ON_EXCEPTION_REACHED_MAX_COUNT"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_RETRY_EXECUTION_ON_EXCEPTION_REACHED_MAX_COUNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("302")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_BATCH_MAIN_INSTANCE_NOT_AVAILABLE {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_BATCH_MAIN_INSTANCE_NOT_AVAILABLE"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_BATCH_MAIN_INSTANCE_NOT_AVAILABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("401")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_EXCEPTION {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_EXCEPTION"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_EXCEPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("403")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_RETRY_REACHED_MAX_COUNT {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_RETRY_REACHED_MAX_COUNT"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_RETRY_REACHED_MAX_COUNT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("303")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_EXCEPTION_NO_RETRY {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_EXCEPTION_NO_RETRY"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_EXCEPTION_NO_RETRY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("205")]
        public int SCHED_RETURN_IN_EXCEPTION_HANDLER_UNEXPECTED_EXCEPTION {
            get {
                return ((int)(this["SCHED_RETURN_IN_EXCEPTION_HANDLER_UNEXPECTED_EXCEPTION"]));
            }
            set {
                this["SCHED_RETURN_IN_EXCEPTION_HANDLER_UNEXPECTED_EXCEPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("201")]
        public int SCHED_RETURN_IN_EXCEPTION_HANDLER_APPLICATION_EXCEPTION {
            get {
                return ((int)(this["SCHED_RETURN_IN_EXCEPTION_HANDLER_APPLICATION_EXCEPTION"]));
            }
            set {
                this["SCHED_RETURN_IN_EXCEPTION_HANDLER_APPLICATION_EXCEPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("202")]
        public int SCHED_RETURN_IN_EXCEPTION_HANDLER_SYSTEM_EXCEPTION {
            get {
                return ((int)(this["SCHED_RETURN_IN_EXCEPTION_HANDLER_SYSTEM_EXCEPTION"]));
            }
            set {
                this["SCHED_RETURN_IN_EXCEPTION_HANDLER_SYSTEM_EXCEPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("203")]
        public int SCHED_RETURN_IN_EXCEPTION_HANDLER_EXCEPTION {
            get {
                return ((int)(this["SCHED_RETURN_IN_EXCEPTION_HANDLER_EXCEPTION"]));
            }
            set {
                this["SCHED_RETURN_IN_EXCEPTION_HANDLER_EXCEPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("204")]
        public int SCHED_RETURN_IN_EXCEPTION_HANDLER_EXCEPTION_IN_EXIT_APPLICATION {
            get {
                return ((int)(this["SCHED_RETURN_IN_EXCEPTION_HANDLER_EXCEPTION_IN_EXIT_APPLICATION"]));
            }
            set {
                this["SCHED_RETURN_IN_EXCEPTION_HANDLER_EXCEPTION_IN_EXIT_APPLICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("206")]
        public int SCHED_RETURN_IN_EXCEPTION_HANDLER_EXCEPTION_IN_ABNORMAL_EXIT {
            get {
                return ((int)(this["SCHED_RETURN_IN_EXCEPTION_HANDLER_EXCEPTION_IN_ABNORMAL_EXIT"]));
            }
            set {
                this["SCHED_RETURN_IN_EXCEPTION_HANDLER_EXCEPTION_IN_ABNORMAL_EXIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("301")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_EXCEPTION_IN_EXIT_APPLICATION {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXCEPTION_IN_EXIT_APPLICATION"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXCEPTION_IN_EXIT_APPLICATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("404")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_EXCEPTION_NO_RETRY {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_EXCEPTION_NO_RETRY"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_EXCEPTION_NO_RETRY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("101")]
        public int SCHED_RETURN_IN_APPLICATION_INITIALIZER_SYSTEM_EXCEPTION {
            get {
                return ((int)(this["SCHED_RETURN_IN_APPLICATION_INITIALIZER_SYSTEM_EXCEPTION"]));
            }
            set {
                this["SCHED_RETURN_IN_APPLICATION_INITIALIZER_SYSTEM_EXCEPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("102")]
        public int SCHED_RETURN_IN_APPLICATION_INITIALIZER_UNHANDLED_EXCEPTION {
            get {
                return ((int)(this["SCHED_RETURN_IN_APPLICATION_INITIALIZER_UNHANDLED_EXCEPTION"]));
            }
            set {
                this["SCHED_RETURN_IN_APPLICATION_INITIALIZER_UNHANDLED_EXCEPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("405")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_DATA_NOT_FOUND {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_DATA_NOT_FOUND"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_MULTIPLE_INVOKE_DATA_NOT_FOUND"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("306")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_COMPLETE_AFTER_STOP_REQUEST {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_COMPLETE_AFTER_STOP_REQUEST"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_COMPLETE_AFTER_STOP_REQUEST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("307")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_COMPLETE_AFTER_STOP_REQUEST_EXCEPTION {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_COMPLETE_AFTER_STOP_REQUEST_EXCEPTION"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_COMPLETE_AFTER_STOP_REQUEST_EXCEPTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("308")]
        public int SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_COMPLETE_AFTER_STOP_REQUEST_DATA_NOT_FOUND {
            get {
                return ((int)(this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_COMPLETE_AFTER_STOP_REQUEST_DATA_NOT_F" +
                    "OUND"]));
            }
            set {
                this["SCHED_RETURN_IN_BATCH_CONTROLLER_EXECUTION_COMPLETE_AFTER_STOP_REQUEST_DATA_NOT_F" +
                    "OUND"] = value;
            }
        }
    }
}
