//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Nidec.Mes.SAPConnector_Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Com.Nidec.Mes.SAPConnector_Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string ErrorMessageCategory {
            get {
                return ResourceManager.GetString("ErrorMessageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 101.
        /// </summary>
        internal static string MOVEMENT_TYPE {
            get {
                return ResourceManager.GetString("MOVEMENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sap user data not found for logged in user[{0}]..
        /// </summary>
        internal static string scce00001 {
            get {
                return ResourceManager.GetString("scce00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured while fetching sap user data for logged in user..
        /// </summary>
        internal static string scce00002 {
            get {
                return ResourceManager.GetString("scce00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rfc Log Exception occurred while logging in to sap [{0}]..
        /// </summary>
        internal static string scce00003 {
            get {
                return ResourceManager.GetString("scce00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred while logging in to sap [{0}]..
        /// </summary>
        internal static string scce00004 {
            get {
                return ResourceManager.GetString("scce00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RfcAbapRuntimeException occured while trying to access rfc function , [exception name : {0}] [message : {1}]..
        /// </summary>
        internal static string scce00005 {
            get {
                return ResourceManager.GetString("scce00005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization not provided for the logged in SAP user..
        /// </summary>
        internal static string scce00006 {
            get {
                return ResourceManager.GetString("scce00006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception occured while trying to access rfc function , [exception name : {0}] [message : {1}].].
        /// </summary>
        internal static string scce00007 {
            get {
                return ResourceManager.GetString("scce00007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception occured while getting sap destination, [exception name : {0}] [message : {1}]..
        /// </summary>
        internal static string scce00008 {
            get {
                return ResourceManager.GetString("scce00008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RfcInvalidStateException occured while trying to access rfc function , [exception name : {0}] [message : {1}]..
        /// </summary>
        internal static string scce00009 {
            get {
                return ResourceManager.GetString("scce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SystemException occured while fetching sap user data for logged in user..
        /// </summary>
        internal static string scce00010 {
            get {
                return ResourceManager.GetString("scce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnhandledException occured while fetching sap user data for logged in user..
        /// </summary>
        internal static string scce00011 {
            get {
                return ResourceManager.GetString("scce00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullReferenceException occured while getting sap destination..
        /// </summary>
        internal static string scce00012 {
            get {
                return ResourceManager.GetString("scce00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RfcInvalidStateException occured while create rfc function instance, [exception name : {0}] [message : {1}]..
        /// </summary>
        internal static string scce00013 {
            get {
                return ResourceManager.GetString("scce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnhandledException occured while create rfc function instance, [exception name : {0}] [message : {1}]..
        /// </summary>
        internal static string scce00014 {
            get {
                return ResourceManager.GetString("scce00014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RfcLogonException occured while create rfc function instance, [exception name : {0}] [message : {1}]..
        /// </summary>
        internal static string scce00015 {
            get {
                return ResourceManager.GetString("scce00015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RfcAbapRuntimeException occured while execute rfcfunction using table parameter, [exception name : {0}] [message : {1}]..
        /// </summary>
        internal static string scce00016 {
            get {
                return ResourceManager.GetString("scce00016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RfcInvalidStateException occured while execute rfcfunction using table parameter , [exception name : {0}] [message : {1}]..
        /// </summary>
        internal static string scce00017 {
            get {
                return ResourceManager.GetString("scce00017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnhandledException occured while execute rfcfunction using table parameter, [exception name : {0}] [message : {1}]..
        /// </summary>
        internal static string scce00018 {
            get {
                return ResourceManager.GetString("scce00018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Name is not specified..
        /// </summary>
        internal static string scce00019 {
            get {
                return ResourceManager.GetString("scce00019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trxcontext value is null in DefaultSAPCommandAdaptor constructor..
        /// </summary>
        internal static string scce00020 {
            get {
                return ResourceManager.GetString("scce00020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Userdata value is null in DefaultSAPCommandAdaptor constructor..
        /// </summary>
        internal static string scce00021 {
            get {
                return ResourceManager.GetString("scce00021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId value is null in DefaultSAPCommandAdaptor constructor..
        /// </summary>
        internal static string scce00022 {
            get {
                return ResourceManager.GetString("scce00022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RfcFunctionname is null in DefaultSAPCommandAdaptor constructor..
        /// </summary>
        internal static string scce00023 {
            get {
                return ResourceManager.GetString("scce00023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RfcDestination is null in DefaultSAPCommandAdaptor constructor..
        /// </summary>
        internal static string scce00024 {
            get {
                return ResourceManager.GetString("scce00024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SapSessionValue is null in RefreshUserSapDestinationAsRequired method of RefreshUserSapDestinationAsRequired class..
        /// </summary>
        internal static string scce00025 {
            get {
                return ResourceManager.GetString("scce00025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId is null in SetAndGetSapUserAndDestinationInCacheDestination method of RefreshUserSapDestinationAsRequired class..
        /// </summary>
        internal static string scce00026 {
            get {
                return ResourceManager.GetString("scce00026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SapSessionValue is null in GetRfcDestination method of RefreshUserSapDestinationAsRequired class..
        /// </summary>
        internal static string scce00027 {
            get {
                return ResourceManager.GetString("scce00027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception occurred while converting Value of [DEFAULT_CACHE_CLEANER_THREAD_INTERVAL : {0}] to integer value..
        /// </summary>
        internal static string scce00028 {
            get {
                return ResourceManager.GetString("scce00028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId is null in GetRfcDestination method of RefreshUserSapDestinationAsRequired class..
        /// </summary>
        internal static string scce00029 {
            get {
                return ResourceManager.GetString("scce00029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId value is null in GetSapUser  method of DefaultSAPCommandAdaptor class..
        /// </summary>
        internal static string scce00030 {
            get {
                return ResourceManager.GetString("scce00030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId is null in GetSapUser method of DefaultSAPRfcDestinationContainer class..
        /// </summary>
        internal static string scce00031 {
            get {
                return ResourceManager.GetString("scce00031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SapSessionValue is null in GetSapUser method of DefaultSAPRfcDestinationContainer class..
        /// </summary>
        internal static string scce00032 {
            get {
                return ResourceManager.GetString("scce00032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trxContext is null in GetSapUser method of DefaultSAPCommandAdaptor class..
        /// </summary>
        internal static string scce00033 {
            get {
                return ResourceManager.GetString("scce00033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Userdata is null in GetSapUser method of DefaultSAPCommandAdaptor class..
        /// </summary>
        internal static string scce00034 {
            get {
                return ResourceManager.GetString("scce00034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SapSessionValue is null in GetSapUser method of DefaultSAPCommandAdaptor class..
        /// </summary>
        internal static string scce00035 {
            get {
                return ResourceManager.GetString("scce00035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no products in the report details.
        /// </summary>
        internal static string scce00036 {
            get {
                return ResourceManager.GetString("scce00036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch and header table batches are inconsistent in the report details.
        /// </summary>
        internal static string scce00037 {
            get {
                return ResourceManager.GetString("scce00037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of finished products in the report details is inconsistent with the number of finished products in the header.
        /// </summary>
        internal static string scce00038 {
            get {
                return ResourceManager.GetString("scce00038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The summary quantity of the middle material of the report schedule is inconsistent with the total number of inputs..
        /// </summary>
        internal static string scce00039 {
            get {
                return ResourceManager.GetString("scce00039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In-parameter is not specified on calling RFC..
        /// </summary>
        internal static string scce00040 {
            get {
                return ResourceManager.GetString("scce00040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromMaterial is not specified in the invo on calling RFC..
        /// </summary>
        internal static string scce00041 {
            get {
                return ResourceManager.GetString("scce00041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToMaterial is not specified in the invo on calling RFC..
        /// </summary>
        internal static string scce00042 {
            get {
                return ResourceManager.GetString("scce00042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RfcDesitination Connection with Desitination Name [{0}]..
        /// </summary>
        internal static string scci00001 {
            get {
                return ResourceManager.GetString("scci00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RfcFunction Execution with Desitination Name [{0}]..
        /// </summary>
        internal static string scci00002 {
            get {
                return ResourceManager.GetString("scci00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed destination from the cache memory using thread of sessionId[{0}]..
        /// </summary>
        internal static string scci00003 {
            get {
                return ResourceManager.GetString("scci00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the remove flag in abnormal scenario for remove destination from the cache memory using thread of sessionId[{0}]..
        /// </summary>
        internal static string scci00004 {
            get {
                return ResourceManager.GetString("scci00004", resourceCulture);
            }
        }
    }
}
