//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.Nidec.Mes.SAPConnector_Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z_GTPPFG1201_MO_OUT")]
        public string RFC_MANUFACTURING_ORDER {
            get {
                return ((string)(this["RFC_MANUFACTURING_ORDER"]));
            }
            set {
                this["RFC_MANUFACTURING_ORDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z_GTSDFG7301_DELIVERY_RFC")]
        public string RFC_DELIVERY_ORDER {
            get {
                return ((string)(this["RFC_DELIVERY_ORDER"]));
            }
            set {
                this["RFC_DELIVERY_ORDER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z_GTSDFG7401_SCAN_DELIVERY")]
        public string RFC_PICKING_LIST {
            get {
                return ((string)(this["RFC_PICKING_LIST"]));
            }
            set {
                this["RFC_PICKING_LIST"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z_GTPPFG0102_STOCK_OUT")]
        public string RFC_STOCK {
            get {
                return ((string)(this["RFC_STOCK"]));
            }
            set {
                this["RFC_STOCK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z_GTPPFG0101_MATERIAL_OUT")]
        public string RFC_MATERIAL {
            get {
                return ((string)(this["RFC_MATERIAL"]));
            }
            set {
                this["RFC_MATERIAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z_GTPPFG1101_MO_CONF_TRANS")]
        public string RFC_MANUFACTURING_ORDER_CONFIRMATION {
            get {
                return ((string)(this["RFC_MANUFACTURING_ORDER_CONFIRMATION"]));
            }
            set {
                this["RFC_MANUFACTURING_ORDER_CONFIRMATION"] = value;
            }
        }
    }
}
